project:
  type: website

website:
  title: "line by line"
  navbar:
    right:
      - index.qmd
      - about.qmd
      - icon: github
        href: https://github.com/ChezkaQuinola
format:
  html:
    theme: vapor
    css: styles.css



